apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: kf5o0ibxh-nodejs 
  janus-idp.io/tekton: kf5o0ibxh-nodejs
  backstage.io/kubernetes-id: kf5o0ibxh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kf5o0ibxh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml