apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kf5o0ibxh-nodejs
  janus-idp.io/tekton: kf5o0ibxh-nodejs
  backstage.io/kubernetes-id: kf5o0ibxh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: kf5o0ibxh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
